//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMini
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorsInfo
    {
        public int IdNum { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string Visiting { get; set; }
        public string TypeOfID { get; set; }
        public string VehicleNo { get; set; }
        public string ContactNo { get; set; }
        public string PurposeOfVisit { get; set; }
        public string Status_ { get; set; }
        public System.DateTime CheckOut { get; set; }
        public System.DateTime CheckIn { get; set; }
    }
}
